%% Define Lumerical variable sweeps
% Michael Nickerson 2021-07-05
%
% Defines a set of variable values to conduct a sweep
%

clear; close('all');

%% Build structure
def_LiNbO3_z_WG;


% Define sweep parameters
sweep = {"wWG", 1.0:0.1:1.5};
sweepName = "LiNbO3_z_mod_wWG";
% buildSweepAndEnqueue(scriptName, script, sweep, 'allvars', setVars, 'sweepname', sweepName, ...
%                      'submitjob', 1, 'session', 'lumerical', 'randomize', 0*0.02, ...
%                      'submitcmd', ["~/lumerical/Q_selected.sh charge", "~/lumerical/Q_selected.sh fde"]);
buildSweepAndEnqueue(scriptName, script, sweep, 'allvars', setVars, 'sweepname', sweepName, ...
                     'submitjob', 0, 'randomize', 0*0.02);

% sweep = {"etchMat", ["'etch'", "'SiO2'"], ...
%          "wWG", 1.0:0.1:1.5, ...
%          "etchDepth", 0.1:0.1:0.5, ...
%          "d", 0.4:0.1:0.8, ...
%          "d2", 0.4:0.1:0.8};
% sweepName = "LiNbO3_z_mod_fullsweep_1";
% buildSweepAndEnqueue(scriptName, script, sweep, 'allvars', setVars, 'sweepname', sweepName, ...
%                      'submitjob', 0, 'randomize', 0.02);
% buildSweepAndEnqueue(scriptName, script, sweep, 'allvars', setVars, 'sweepname', sweepName, ...
%                      'submitjob', 1, 'session', 'lumerical', 'randomize', 0.02, ...
%                      'submitcmd', ["~/lumerical/Q_selected.sh charge", "~/lumerical/Q_selected.sh fde"]);
