%% Define Lumerical variable sweeps
% Michael Nickerson 2021-07-05
%
% Defines a set of variable values to conduct a sweep
%

clear; %close('all');

%% Build structure
def_GaAs_SSC_AR8;


% Define sweep parameters
sweep = {"lActive", 0, ...
         "lWG", 2, "lFS", 0.5, ...
         "simY", 6, ...
         "etch2", 3.0, "wWG2", 20.0, ...
         "etch1", 3.0, "wWG1", 2.0, ...
         "wSSC1", 5, "lSSC1", 80:5:100};
sweepName = "AR8_passive_SSC_deep";

% sweep = {"lActive", 0, "sim2D", 0, ...
%          "lWG", 2, "lFS", 0.5, ...
%          "simY", 6, ...
%          "etch2", 3.0, "wWG2", 20.0, ...
%          "etch1", 3.0, "wWG1", 2.0, ...
%          "wSSC1", 5, "lSSC1", 80:5:100};
% sweepName = "AR8_passive_SSC_deep_FDTD";

% sweep = {"lActive", 0, "sim2D", 2, ...
%          "lWG", 10, "lFS", 4, ...
%          "wWG1", 5, "wWG2", 5, ...
%          "lSSC1", 0, "lSSC2", 0, "lStrt", 0, ...
%          "aFacet", 0:0.1:16};
% sweepName = "AR8_passive_deep_aFacet";

% sweep = {"lActive", 0, "sim2D", 0, ...
%          "lWG", 15, "lFS", 3, ...
%          "wWG1", 5, "wWG2", 5, ...
%          "lSSC1", 0, "lSSC2", 0, "lStrt", 0, ...
%          "aFacet", [0:0.1:18]};
% sweepName = "AR8_passive_deep_aFacet_FDTD";


%% Build scripts locally
buildSweepAndEnqueue(scriptName, script, sweep, 'allvars', setVars, 'sweepname', sweepName, ...
                     'submitjob', 0, 'randomize', 0);
